### ISSUE TITLE
make it responsive

### ISSUE THREAD

**Issue by subashsigdel** [Samitasunuwar0/todoapp#1]
- Try making it responsive 
- Add complete button 
- Add delete button to delete the completed task
- ![Screenshot from 2022-08-30 20-28-55](https://user-images.githubusercontent.com/77682103/187481560-ea905949-1c9f-4c77-a356-baf34943c2e0.png)

**Comment by Samitasunuwar0** [comment]
![image](https://user-images.githubusercontent.com/108125270/187574919-636473f6-4e8f-4219-9b3c-f2817ea2db6f.png)

I have added complete and delete button already which was finished that day...how it didn't showed there??
